<?php

namespace App\Filament\Resources\DataPersonalResource\Pages;

use App\Filament\Resources\DataPersonalResource;
use App\Helpers\Helpers;
use App\Repositories\UserRepository;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Resources\Pages\EditRecord;
use Filament\Notifications\Notification;
use App\Filament\Resources\CustomerResource\Pages;
use Filament\Resources\Pages\Page;

class EditDataPersonal extends EditRecord
{
    protected static string $resource = DataPersonalResource::class;

    public function getTitle(): string
    {
        return "Editar dados pessoais";
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function getSavedNotification(): ?Notification
    {
        return Helpers::customNotification(
            'success',
            'Sucesso',
            'Dados pessoais registrados com sucesso!',
            'heroicon-s-check-circle',
            'success'
        );

    }

    public function getBreadcrumbs(): array
    {
        return [];
    }

    public function getCancelFormAction(): Action
    {
        return Action::make('Voltar')
            ->extraAttributes(['onclick' => 'window.history.back()'])
            ->color('primary'); // TODO: Change the autogenerated stub
    }

}
